Sanketa/daily simulation
drewmresnick/PondModelBD pull request #6
Opened 2021-06-22 17:00 UTC by skadam02

merging daily code to main

2021-06-23 13:40 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +    for day_argue in list(range(1, 1095)):
I still have not been able to find exactly where we got the eqns for calculating water temperature using energy heat flux.. I will keep looking in the papers we read but am not sure at the moment! Whoops

2021-06-23 20:10 UTC, drewmresnick requested changes

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +    for day_argue in list(range(1, 1095)):
In Culberson and Piedrahita they give the equation which is expressed with heat flux as a derivative solving for the change in heat over the change in time for a given period of time. So this version of the equation is including only the change in heat flux at a single point in time instead of the rate of change but they are doing the same things.

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +        phi_c = calculate_phi_c(T_wk, day_argue)
temperature is converted to degrees celcius in the function which is consistent with units in the C&P paper

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +    global T_wk
I am unfamiliar with global variables - when using a global variable does it automatically get updated inside and outside of the function? Since it is first defined outside the function and then the global variable is defined inside the function? Just want to make sure that it updates the variable with the new value each time and is not just passing through the same water temperature at each time step.

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +        print(phi_net)
In C&P this equations solves for Temperature of Vi at time t in degrees Celcius - not in kelvin. Should these values in the function be converted to celcius?

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +        H_t_1 = T_wk * water_heat_capacity * water_density
The heat capacity of water has units kJ / kg C - which is why temperature needs to be in celcius not kelvin

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +        H_t_1 = T_wk * water_heat_capacity * water_density
Just double checking that the input for water temperature here will be the water temperature from the previous time step? Is the variable being updated with each step through the model?

2021-06-23 20:10 UTC, drewmresnick commented on mixed_pond_experimental/daily_code.py
> +    T_wk_C = np.array(T_wk_vec) - 273.15
So I think in the calculation of the new temperature we will need Temperature in celcius not in Kelvin for the actual calculation and not just for plotting

2021-06-24 16:45 UTC, skadam02 commented on mixed_pond_experimental/daily_code.py
> +    global T_wk
yes the idea is that it is updated every iteration, we can add a breakpoint and check the T_wk values in the loop

2021-06-29 17:56 UTC, drewmresnick approved these changes

2021-06-29 18:08 UTC, merged