Sanketa/sensitivity setup
drewmresnick/PondModelBD pull request #8
Opened 2021-07-15 21:10 UTC by skadam02

sensitivity conditions set up

2021-07-16 13:20 UTC, drewmresnick requested changes

2021-07-16 13:20 UTC, drewmresnick commented on mixed_pond_experimental/sensitivity_setup.py
> +    plt.plot(data['degC_avg'])
My understanding here is that you are plotting the model results against the averaged temperatures from the input data - however is this the observed water temperature from the pond? I cannot remember exactly, however when I was making the plots I had a completely separate file for the observed air and water temperature. So I want to just confirm if this is the observed data or if this is the from the POWER dataset? @skadam02

2021-07-16 13:20 UTC, drewmresnick commented on mixed_pond_experimental/sensitivity_setup.py
> +watertemp = pd.read_csv('Realtime_watertemp.csv')
Or is this a file of the observed data? @skadam02

2021-07-16 13:20 UTC, drewmresnick commented on mixed_pond_experimental/sensitivity_setup.py
> +    plt.show()
Can you add the legend with labels to the plot?

`plt.plot(watertemp['day_avg'], label="observed water temp")`
`plt.legend()`
`plt.show()`

2021-07-17 22:22 UTC, closed without merging

2021-07-17 22:22 UTC, skadam02 commented
making changes per comments